version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    volumes:
      - ./src:/app/src
      - sqlite_data:/app/data
    depends_on:
      - db

  db:
    image: keinos/sqlite3:latest
    volumes:
      - sqlite_data:/data
    command: ["/bin/sh", "-c", "while true; do sleep 1; done"]

volumes:
  sqlite_data:
    driver: local