apiVersion: apps/v1
kind: Deployment
metadata:
  name: leave-management-backend
  labels:
    app: leave-management-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: leave-management-backend
  template:
    metadata:
      labels:
        app: leave-management-backend
    spec:
      containers:
      - name: leave-management-backend
        image: leave-management-backend:latest
        ports:
        - containerPort: 3000
        env:
        - name: NODE_ENV
          value: "production"
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: leave-management-config
              key: db_host
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: leave-management-secrets
              key: jwt_secret
        resources:
          requests:
            memory: "256Mi"
            cpu: "200m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 15
          periodSeconds: 20
---
apiVersion: v1
kind: Service
metadata:
  name: leave-management-backend-service
spec:
  selector:
    app: leave-management-backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: ClusterIP