apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: leave-management-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  ingressClassName: nginx
  rules:
  - http:
      paths:
      - path: /api
        pathType: Prefix
        backend:
          service:
            name: leave-management-backend-service
            port:
              number: 80
      - path: /microservice
        pathType: Prefix
        backend:
          service:
            name: leave-management-microservice-service
            port:
              number: 80
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: leave-management-config
data:
  db_host: "localhost"
---
apiVersion: v1
kind: Secret
metadata:
  name: leave-management-secrets
type: Opaque
data:
  jwt_secret: base64_encoded_jwt_secret
  api_key: base64_encoded_api_key