name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci

      - name: Install ESLint dependencies
        run: npm install eslint @eslint/js globals --save-dev

      - name: Run linting
        run: npm run lint

      - name: Run tests
        run: npm test

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/leave-management:latest

      # To make this step work:
      # 1. Sign up for a Snyk account at https://snyk.io
      # 2. Get your Snyk API token from Account Settings
      # 3. Add the token as a GitHub secret named 'SNYK_TOKEN'
      - name: Run security scan
        uses: snyk/actions/docker@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          image: ${{ secrets.DOCKER_HUB_USERNAME }}/leave-management:latest
          args: --severity-threshold=high
          # Optional: add --file=Dockerfile if you want to test the Dockerfile itself